#!/bin/sh

enabled=$(xinput list-props 'AT Translated Set 2 keyboard' | awk 'FNR == 2 { print $4 }')
if [ $button -eq 1 ]
then
  if [ $enabled -eq 1 ]
  then
  xinput disable 'AT Translated Set 2 keyboard'
  echo 󰹋
  else
  xinput enable 'AT Translated Set 2 keyboard'
  echo 
  fi
else
  if [ $enabled -eq 1 ]
  then
  echo 
  else
  echo 󰹋
  fi
fi

# 󰌌
# 󰌐
# 󰹋
# 
