#!/bin/sh

regex="Front Left: Playback [[:digit:]]* \[([0-9]*%)\] \[(on|off)\]$"

line="$(amixer | grep 'Front Left: Playback')"

if [[ "$line" =~ $regex ]]; then
  if [[ ${BASH_REMATCH[2]} == off ]]; then
    echo " mute"
  else
    echo " ${BASH_REMATCH[1]}"
  fi
else
  echo "???"
fi
