#!/bin/sh

# e.g.
#           Link Quality=65/70  Signal level=-45 dBm

regex="\s+Link Quality=([[:digit:]]+)/([[:digit:]]+)"

line="$(iwconfig 2> /dev/null | grep 'Link Quality')"

ssid=$(iwgetid -r)

if [[ "$line" =~ $regex ]]; then
    (( x = ${BASH_REMATCH[1]} * 100 ))
    (( percent = $x / ${BASH_REMATCH[2]} ))
    printf " %s (%d%%)\n" $ssid $percent
else
  echo "???"
fi
